[package]
name = "jamess-nguyen/roblox-stock-exchange"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

[dev-dependencies]

[server-dependencies]
